### PR TITLE
Updated Fyber Marketplace to 7.5.2

### PR DESCRIPTION
**Pull request by sagia-inneractive**

### CODE REVIEW

**Comment by sagia-inneractive** [comment]
@googlebot I signed it!

**Comment by sagia-inneractive** [comment]
@googlebot I signed it!

**Comment by sagia-inneractive** [comment]
@googlebot I signed it!

**Comment by sagia-inneractive** [comment]
Sorry for the spam of mentions, trying to troubleshoot our CLA issue

**Comment by joshuajplagonera** [comment]
Hi @sagia-inneractive 

We made our own PR with your changes to resolve the CLA issues. Can you take a look at #235 ? Let me know if you have any questions.

**Comment by sagia-inneractive** [comment]
@joshuajplagonera Looks good, thank you for the help! we have contacted the cla-submissions email in order to get the issue resolved.

**Pull request closed without merging**
