### PR TITLE
Revert "Update AdColony to 3.3.4 and pass on npa info if available for GDPR purposes"

### PR DESCRIPTION
**Pull request by spilaka**
Reverts googleads/googleads-mobile-android-mediation#80

### CODE REVIEW

**Comment by brittmullen** [comment]
Hello, I'm just curious about the reason behind this revert. Is there any feedback on what we need to do differently before submitting another pull request with changes to pass consent and bump version to 3.3.4? Thanks!

**Comment by brittmullen** [comment]
@spilaka just bumping this request, any updates here?

**Comment by spilaka** [comment]
Hello, here I guess we don't need to pass the "npa" value in app options. From the documentation of Adcolony, what we observed that the GDPR consent is a static method. So, publisher will import the sdk and he can use the consent using that static method.

**Comment by brittmullen** [comment]
Our app options aren't static, but are passed through static configure() or setAppOptions() methods - but these are handled by the adapter. If the concern is us forwarding consent from AdMob directly via the "npa" value we can instead collect this consent ourselves via the AdColonyBundleBuilder. Would that work?

**Comment by spilaka** [comment]
Sure, that works. You can do that through AdColonyBundleBuilder.

**Pull request merged**
