### PR TITLE
AdColony Update for 3.0.6.1

### PR DESCRIPTION
**Pull request by hrcronin**
This fixes issues that we've found in our adapter. I've also updated the changelog to reflect the new version number for the updated Adapter.

### CODE REVIEW

**Comment by ericleich** [comment]
@hrcronin For some reason your diff looked like the entire adapter based on some changes back in December. So instead, we separately committed the change to fix the NPE with this commit: https://github.com/googleads/googleads-mobile-android-mediation/commit/a5bee7c01686d26ad1687ae22314e8f10c68344c

Let us know if this looks good, and we'll publish the latest compiled adapter version on Bintray (which we've confirmed runs against the AdColony 3.1.2 SDK).

**Comment by hrcronin** [comment]
Good morning,

I had just merged in the fork of my repo to the master fork, instead of just a single commit, so my apologies for the confusion. I checked out that commit (a5bee7c) and everything looks correct.

Let me know if you need anything else from me. Thanks!

Best,

Heather Cronin

On Sun, Apr 16, 2017 at 7:45 PM Eric Leichtenschlag

<
mailto:Eric Leichtenschlag <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/hrcronin
For some reason your diff looked like the entire adapter based on some changes back in December. So instead, we separately committed the change to fix the NPE with this commit:
https://github.com/googleads/googleads-mobile-android-mediation/commit/a5bee7c01686d26ad1687ae22314e8f10c68344c

Let us know if this looks good, and we'll publish the latest compiled adapter version on Bintray (which we've confirmed runs against the AdColony 3.1.2 SDK).

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/googleads/googleads-mobile-android-mediation/pull/6#issuecomment-294384007
, or

**Comment by ericleich** [comment]
Thanks for confirming Heather! Nothing more needed from your side. We will roll out the new compiled AdColony adapter and host on Bintray. You can look [here](https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.adcolony) for version 3.1.2.0 of the adapter.

**Comment by hrcronin** [comment]
Hi Eric, 

I just checked out version 3.1.2.0 and I the only file I see under files for that version is “maven-metadata.xml”. Does that mean that 3.1.2.0 is in the middle of being updated with the other necessary files (*.aar, etc.)? Just wanted to check in case the were missed during the update process.

Thanks!

best,

Heather Cronin

On Mon, Apr 17, 2017 at 12:25 PM Eric Leichtenschlag

<
mailto:Eric Leichtenschlag <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Thanks for confirming Heather! Nothing more needed from your side. We will roll out the new compiled AdColony adapter and host on Bintray. You can look
https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.adcolony
for version 3.1.2.0 of the adapter.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/googleads/googleads-mobile-android-mediation/pull/6#issuecomment-294534429
, or

**Comment by ericleich** [comment]
Hi Heather,

The files should be there now. Indeed, we had already put up a build for 3.12.0 but hadn't published it yet.

**Pull request closed without merging**
