### PR TITLE
Initialize Mintegral SDK in a background thread (to avoid ANRs).

### PR DESCRIPTION
**Pull request by thanvirm**
Initialize Mintegral SDK in a background thread (to avoid ANRs).

### CODE REVIEW

**Comment by junjunsong** [comment]
Sorry, the internal implementation of these two methods is the same. If you want to implement asynchronous operations, you need to implement them yourself

**Comment by thanvirm** [comment]
> Sorry, the internal implementation of these two methods is the same. If you want to implement asynchronous operations, you need to implement them yourself

Thank you junjunsong@ for the input. 

Two follow-up questions:
1. We see 1 million ANR reports per month for this function call. Have you also received complaints about ANRs for this function call? Would you be able to update the implementation of the init() call to avoid ANR?
2. To avoid ANR, we can call the init() function on a background thread instead of the main thread. Would you recommend calling init() on a background thread? Do you think that would fix the ANR?

Thanks!

**Comment by junjunsong** [comment]
> > Sorry, the internal implementation of these two methods is the same. If you want to implement asynchronous operations, you need to implement them yourself
> 
> Thank you junjunsong@ for the input.
> 
> Two follow-up questions:
> 
> 1. We see 1 million ANR reports per month for this function call. Have you also received complaints about ANRs for this function call? Would you be able to update the implementation of the init() call to avoid ANR?
> 2. To avoid ANR, we can call the init() function on a background thread instead of the main thread. Would you recommend calling init() on a background thread? Do you think that would fix the ANR?
> 
> Thanks!

We will make an optimization in future versions. Make init an asynchronous implementation. Currently, you can first call the init method in the background thread, but be sure to ensure that the init method is executed before calling the load method

**Comment by thanvirm** [comment]
> > > Sorry, the internal implementation of these two methods is the same. If you want to implement asynchronous operations, you need to implement them yourself
> > 
> > 
> > Thank you junjunsong@ for the input.
> > Two follow-up questions:
> > 
> > 1. We see 1 million ANR reports per month for this function call. Have you also received complaints about ANRs for this function call? Would you be able to update the implementation of the init() call to avoid ANR?
> > 2. To avoid ANR, we can call the init() function on a background thread instead of the main thread. Would you recommend calling init() on a background thread? Do you think that would fix the ANR?
> > 
> > Thanks!
> 
> We will make an optimization in future versions. Make init an asynchronous implementation. Currently, you can first call the init method in the background thread, but be sure to ensure that the init method is executed before calling the load method

I have updated the code to call the init method in the background thread. Please review. Thanks!

**Review by junjunsong — APPROVED** [review]

**Pull request closed without merging**
