### PR TITLE
Fyber Marketplace 7.8.4

### PR DESCRIPTION
**Pull request by sagia-inneractive**

### CODE REVIEW

**Comment by sagia-inneractive** [comment]
@ericleich i think the cla bot dont like the merge commit (fork sync), should i create a fresh pr ?

**Comment by ericleich** [comment]
@sagia-inneractive yeah, can you try a fresh PR first?

**Comment by sagia-inneractive** [comment]
commit rebased to match latest upstream, cla bot seems to be ok with that.

**Comment by joshh-devrel** [comment]
@sagia-inneractive 
The changes in this PR were already added to the adapter via Google internal changes.
This PR can now be closed.

**Pull request closed without merging**
