### PR TITLE
InMobi 9.0.5 Support

### PR DESCRIPTION
**Pull request by im-lakshya**
* Removed the deprecated API
* Added new APIs

### CODE REVIEW

**Comment by RajSuvariya-InMobi** [comment]
@googlebot I fixed it

**Comment by RajSuvariya-InMobi** [comment]
@googlebot I consent

**Comment by RajSuvariya-InMobi** [comment]
@googlebot I fixed it.

**Comment by im-lakshya** [comment]
@googlebot I consent

**Comment by prabodhprakash** [comment]
@googlebot I consent

**Comment by RajSuvariya-InMobi** [comment]
@joshuajplagonera Please review.

**Comment by RajSuvariya-InMobi** [comment]
@joshuajplagonera I have reformatted the PR with the guideline suggested by you. PTAL

**Pull request merged**
