### PR TITLE
AppLovin/Add Native Ads Adapter

### PR DESCRIPTION
**Pull request by thomasmso**

### CODE REVIEW

**Comment by joshuajplagonera** [comment]
Hi @thomasmso ,
Please resolved the conflict files before we can continue with the review.

**Comment by thomasmso** [comment]
I signed it!

**Comment by joshuajplagonera** [comment]
@thomasmso Just to confirm, does the AppLovin SDK not support callbacks when the Native Ad was tapped?

**Comment by thomasmso** [comment]
Correct - We have no callbacks for when our native ads gets tapped as it is a pretty raw ad format.

**Pull request merged**
